version: '3'
services:
  app:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    networks:
      - app_network
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network
networks:
  app_network: